import type { NettData } from './types';

export const emptyData: NettData = {
  profile: {
    id: '',
    full_name: null,
    display_currency: 'AED',
    theme: 'system',
    freshness_days: 31,
    enabled_countries: ['AE', 'IN'],
    enabled_currencies: ['AED', 'INR'],
  },
  workspaces: [],
  accounts: [],
  debts: [],
  debtEvents: [],
  receivables: [],
  receivableEvents: [],
  investments: [],
  commitments: [],
  reserves: [],
  transactions: [],
  creditCards: [],
  spaces: [],
  investmentValues: [],
  forecastScenarios: [],
  budgetLines: [],
  fxRates: {
    AED_USD: 0.2723,
    USD_AED: 3.6725,
    AED_INR: 22.58,
    INR_AED: 0.0443,
    USD_INR: 82.92,
    INR_USD: 0.0121,
  },
  fxRateSource: 'Nett baseline rates',
  fxRatesUpdatedAt: null,
};
